### ISSUE TITLE
Shield Prediction for other's shields

### ISSUE THREAD

**Issue by Fanquar** [Zidras/ElvUI_ProjectZidras#12]
shield prediction for another player's shields seems to not be functioning properly, only showing the minimum amount absorbed assuming no spellpower modification.

Could this be fixed by caching at least the player's gear, even if ignoring procs, and assuming the gear (mainly, spellpower on gear) does not change until after I relog? at least give a ballpark prediction for how much absorb someone elses shield should be doing

**Comment by Zidras** [comment]
Absorbs are handled via Kader's specialized absorbs lib, maybe @bkader can help here when he's available

**Comment by bkader** [comment]
Just like **heals prediction** that requires both ends to have `LibHealComm`, **shields prediction** require both ends to have either:
1. `AbsorbsMonitor-1.0`, that only communicates stats to players having this lib, or
2. `SpecializedAbsorbs-1.0`, that communicates to both players having this lib or the first one.

I have tested it with both ends having the addon enabled, it works fine for both heals and shields predictions, but if other players don't have it, it will either not work at all or fallback to default values since stats and multipliers weren't sent from others. They should at least have this addon or [Grid2](https://github.com/bkader/Grid2-WoTLK) if you want to see it working properly.

Keep in mind that anything that requires a library and addon comms requires both ends to have it, otherwise things won't work or simply fallback to default values.

**Comment by Zidras** [comment]
Thanks Kader for clarifying
