### ISSUE TITLE
Absorb Prediction

### ISSUE THREAD

**Issue by Multibow** [Zidras/ElvUI_ProjectZidras#13]
There is a problem with Absorb Prediction, if the function is disabled then custom text does not work to track how much absorb I have on me in text format only.
I needed to enable / disable it for it to work with custom text when I tested yesterday.
But it did not work as they should in combat anyway, it showed completely wrong absorb

**Comment by Zidras** [comment]
> There is a problem with Absorb Prediction, if the function is disabled then custom text does not work to track how much absorb I have on me in text format only.
> I needed to enable / disable it for it to work with custom text when I tested yesterday.

This is most likely due to the initialization callback that relies on the db option enabled. I'll fix it when I have some free time to work on PZ.


> But it did not work as they should in combat anyway, it showed completely wrong absorb

This cannot be fixed, as it relies on addon comms, meaning that both need to have an addon with the lib. Read Kader's response for a more comprehensive explanation: https://github.com/Zidras/ElvUI_ProjectZidras/issues/12#issuecomment-1084470213

**Comment by Zidras** [comment]
This is intended. Disabling the entire panel will not run the required functions. If you wish to use PZ tags, you must have the specified unit running PZ absorbs module. If you don't want an absorbs bar, then simply disable them like so:

https://user-images.githubusercontent.com/10605951/187038145-1c8f5531-4e23-44a4-bea1-5c7bce6464c9.mp4
